Lesson 1: add adminer try 3
GoSum215/fefu_backend_2_3 pull request #5
Opened 2021-10-30 03:16 UTC by GoSum215

Также в .env была добавлена переменная ADMINER_PORT=8080
База данных на сайте открывается, проблем, теперь, пока не возникает

2021-11-01 15:33 UTC, chrn-feip requested changes
После того как сделаете правки тут и обновите мастер, поредактируйте этот PR, указав таргет - новый мастер, а не старый.

2021-11-01 15:33 UTC, chrn-feip commented on docker-compose.yml
> +        - 8080:8080
1. Вот здесь нужно использовать переменную окружения. См. как сделано в pgsql или laravel.test. И переменную эту нужно добавить в два места: .env.example (который попадёт в коммит, так какое угодно значение может быть в т.ч. пустое) и .env (это локальный файл, вне версионирования гита, там значение нужное вам, тот порт, который вы готовы выделить админеру).

2. Соблюдайте табуляцию, это может быть важно в yml файлах, см. как в других секциях отступы сделаны.

2021-11-04 02:56 UTC, GoSum215 commented
Не зная, как правильнее сделать, я просто удалил все файлы из репозитория
Поэтому сейчас не придётся менять мастер

2021-11-04 05:05 UTC, chrn-feip commented
> Не зная, как правильнее сделать, я просто удалил все файлы из репозитория Поэтому сейчас не придётся менять мастер

Вам же в issue написано, что нужно сделать с мастером. Сделать его заново, чтобы там был одни единственный коммит с проектом в том нетронутом состоянии, в котором вы его скачали командой из документации ларавеля.

2021-11-04 05:08 UTC, chrn-feip commented
А вот после того когда вы сделаете хорошую ветку мастер, тогда надо будет сменить тут
![image](https://user-images.githubusercontent.com/40585429/140261071-a1afed41-e5c9-40fb-8e8f-ffb24f965e2f.png)

into main на into <ваш новый мастер>

2021-11-04 07:46 UTC, closed without merging